[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyclock"
version = "1.1.1"
authors = [
  { name="Seth Bailey", email="phskbailey@gmail.com" },
]
description = " An open-source, python library to viewing dates and times"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Knabberpause/pyclock"
"Bug Tracker" = "https://github.com/Knabberpause/pyclock/issues"